services:
  db:
    image: postgres:16
    env_file:
      - db.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5431:5431"
  bot:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
volumes:
  pgdata:
